URI = "mongodb+srv://iandan874:iamiandaniel@cluster0.wb90azp.mongodb.net/?retryWrites=true&w=majority"
OPENAI_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyDPReGtYLTf3CUT0T-SdqFn5G28h5sl16M"
